import networkx
import community
import matplotlib.pyplot as plt
import os
import pandas as pd
from pyvis import network as net
from pprint import pprint
import json

'''
Script for communities analysis and viz generated by networkx
input: data/reddit_network.gml (net)
output: data/reddit_network_communities.gml (net with communities)
output: output/reddit_network_communities.html (viz)
'''

G = networkx.read_gml('../data/reddit_network.gml')
partition = community.best_partition(G)
modularity = community.modularity(partition, G)
print("Modularity: ", modularity, "(modularity close to 1 means that the graph is well partitioned)")
print("Number of communities: ", len(set(partition.values())))

data_to_save = {
    "modularity": modularity,
    "number_of_communities": len(set(partition.values())),
    "partition": partition
}

# Zapis do pliku w formacie JSON
with open('../data/reddit_network_communities.json', 'w') as f:
    json.dump(data_to_save, f)

for node in G.nodes:
    G.nodes[node]['community'] = partition[node]
networkx.write_gml(G, '../data/reddit_network_communities.gml')

# save graph as dataframe
df_com = pd.DataFrame.from_dict(partition, orient='index')
df_com.reset_index(inplace=True)
df_com.columns = ['author', 'community']
df_com['community'] = df_com['community'].astype(str)
df_com.to_csv('../data/reddit_network_communities.csv', index=False)

# create df with author and community
df = {}
for node in G.nodes(data=True):
    df[node[0]] = node[1]['community']
df = pd.DataFrame.from_dict(df, orient='index')
df.reset_index(inplace=True)
df.columns = ['author', 'community']
df['community'] = df['community'].astype(str)
# print unique communities
print("Unique communities: ")
pprint(df['community'].unique())

color_map = dict.fromkeys(set(partition.values()))
for i in range(len(color_map)):
    color_map[i] = '#' + os.urandom(3).hex()

nodes = []
for idx, row in G.nodes(data=True):
    nodes.append((idx, {'color': color_map[row['community']]}))

G2 = networkx.Graph()
G2.add_nodes_from(nodes)
G2.add_edges_from(G.edges())
nt = net.Network(height="750px", width="100%", bgcolor="#222222", font_color="white", notebook=True)
nt.from_nx(G2)
nt.show_buttons(filter_=['physics'])
nt.show("../output/reddit_network_communities.html")
